PORT: # サーバのポート
  require: false
  default: 8880

# Twitter用のAPI KEY
API_KEY:
  require: true
API_SECRET:
  require: true
TOKEN:
  require: true
TOKEN_SECRET:
  require: true

# firebase
FIREBASE_EMAIL:
  require: true
FIREBASE_PASSWORD:
  require: true

# dyno metadata()
HEROKU_RELEASE_VERSION:
  require: true
