port: # サーバのポート
  require: false
  default: 8880
API_KEY:
  require: true
API_SECRET:
  require: true
TOKEN:
  require: true
TOKEN_SECRET:
  require: true

MYDNS_MASTER_ID:
  require: false
MYDNS_PASSWORD:
  require: false