name: Denopendabot
on:
  schedule:
    - cron: "0 0 * * *" # modify to your convinient time
  workflow_dispatch:
    
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          event-type: denopendabot-run