name: Deno Test

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43.1
      - name: Run check
        run: |
          deno task check